// routines.js — lazy local-first scheduled checklists with shared household people.
(function(){
  const core=window.routinesCore;
  const state={data:null,summary:null,day:null,view:"today",date:core.dateKey(new Date()),form:null,confirm:null,busy:false,priorFocus:null,focusSerial:0,expanded:new Set(),initialDayExpansion:true,stepBatch:{timer:0,flight:null,changes:new Map()}};
  const root=()=>document.getElementById("routines"),body=()=>document.getElementById("routines-body"),tabs=()=>document.getElementById("routines-tabs"),status=()=>document.getElementById("routines-status");
  const isOpen=()=>!!root()?.classList.contains("show");
  const people=()=>Array.isArray(state.data?.people)?state.data.people:[];
  const routines=()=>Array.isArray(state.data?.routines)?state.data.routines:[];
  const settings=()=>state.data?.settings||{};
  const setStatus=text=>{const node=status();if(node)node.textContent=text||"";};
  const list=value=>Array.isArray(value)?value:[];
  const dateObject=value=>new Date(String(value||"")+"T12:00:00");
  const humanDate=value=>{const date=dateObject(value);return Number.isNaN(+date)?String(value||""):date.toLocaleDateString(undefined,{weekday:"long",month:"long",day:"numeric"});};
  const clone=value=>JSON.parse(JSON.stringify(value||{}));
  const sessionKey=session=>`${session.routineId||""}/${session.assignmentId||""}`;
  function button(label,cls,fn){const node=el("button",cls||"rt-action",label);node.type="button";bindTap(node,fn);return node;}
  function focusKey(input,key){if(key)input.dataset.rtFocusKey=key;return input;}
  function field(label,value,mode,placeholder,multiline,key){const wrap=el("label","rt-field"),caption=el("span","",label),input=document.createElement(multiline?"textarea":"input");input.value=value||"";input.placeholder=placeholder||"";input.autocomplete="off";input.dataset.oskMode=mode||"text";focusKey(input,key);input.addEventListener("focus",()=>showOSKFor(input));input.addEventListener("pointerup",()=>{input.focus();showOSKFor(input);},{passive:true});wrap.append(caption,input);return{wrap,input};}
  function select(label,value,options,onChange,key){const wrap=el("label","rt-field"),caption=el("span","",label),node=document.createElement("select");focusKey(node,key);for(const [keyValue,name] of options){const option=document.createElement("option");option.value=keyValue;option.textContent=name;option.selected=keyValue===value;node.appendChild(option);}node.addEventListener("change",()=>onChange(node.value));wrap.append(caption,node);return{wrap,node};}
  function captureFormFocus(){const active=document.activeElement,key=active?.dataset?.rtFocusKey;if(!state.form||!key||!body()?.contains(active))return null;let start=null,end=null;try{start=active.selectionStart;end=active.selectionEnd;}catch(_){}return{key,start,end};}
  function restoreFormFocus(snapshot){if(!snapshot||!state.form)return;requestAnimationFrame(()=>{if(!isOpen()||!state.form)return;const input=[...body().querySelectorAll("[data-rt-focus-key]")].find(node=>node.dataset.rtFocusKey===snapshot.key);if(!input)return;try{input.focus({preventScroll:true});}catch(_){input.focus();}if(Number.isInteger(snapshot.start)&&typeof input.setSelectionRange==="function"){try{input.setSelectionRange(snapshot.start,snapshot.end);}catch(_){}}});}
  async function request(path,payload){const response=await fetch(path,{method:payload?"POST":"GET",headers:payload?{"Content-Type":"application/json",Accept:"application/json"}:undefined,body:payload?JSON.stringify(payload):undefined,cache:"no-store"});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.error||"Routines are unavailable");return data;}
  function accept(response){state.data=response.state||response;state.summary=response.summary||{};if(response.day)state.day=response.day;const summary=state.summary||{};setStatus(`${summary.due||0} due today · ${summary.completed||0} complete`);}
  async function load(){accept(await request("/api/routines"));state.day=await request("/api/routines/day?date="+encodeURIComponent(state.date));render();}
  async function refreshDay(){state.day=await request("/api/routines/day?date="+encodeURIComponent(state.date));}
  async function mutate(path,payload,message){if(state.busy)return;state.busy=true;root()?.classList.add("busy");setStatus("Saving…");try{const response=await request(path,{...(payload||{}),dayDate:state.date});accept(response);state.form=null;state.confirm=null;if(message)setStatus(message);render();}catch(error){setStatus(error.message||"Could not save Routines.");render();}finally{state.busy=false;root()?.classList.remove("busy");}}
  function openPeopleControl(origin){if(typeof window.openDashboardPeopleControl!=="function"){setStatus("People management is unavailable until Dashboard Control loads.");return;}const date=state.date;window.openDashboardPeopleControl({origin:origin||document.activeElement,close:closeRoutines,reopen:()=>openRoutines({date})}).catch(error=>setStatus("Could not open People · "+(error&&error.message?error.message:"try again")));}
  function managePeopleButton(className){let node;node=button("Manage people",className||"rt-action",()=>openPeopleControl(node));return node;}
  function nav(){const target=tabs();target.replaceChildren();for(const [id,label] of [["today","Today"],["routines","Routines"],["history","History"],["settings","Settings"]]){const node=button(label,"rt-tab",()=>{state.view=id;state.form=null;state.confirm=null;hideOSK();render();});node.setAttribute("aria-pressed",String(state.view===id));target.appendChild(node);}}
  function dateControls(){const row=el("div","rt-date-controls");row.append(button("‹ Previous","rt-action",()=>{const d=dateObject(state.date);d.setDate(d.getDate()-1);state.date=core.dateKey(d);state.initialDayExpansion=true;load().catch(error=>setStatus(error.message));}),button(state.date===core.dateKey(new Date())?"Today":"Go to today","rt-action primary",()=>{state.date=core.dateKey(new Date());state.initialDayExpansion=true;load().catch(error=>setStatus(error.message));}),button("Next ›","rt-action",()=>{const d=dateObject(state.date);d.setDate(d.getDate()+1);state.date=core.dateKey(d);state.initialDayExpansion=true;load().catch(error=>setStatus(error.message));}));return row;}
  function findDaySession(key){for(const person of list(state.day?.people)){for(const session of list(person.sessions)){if(sessionKey(session)===key)return session;}}return null;}
  function applySessionStep(session,stepID,checked){const completed=core.completed(session);if(checked)completed.add(String(stepID));else completed.delete(String(stepID));session.completedStepIds=[...completed];const total=list(session.steps).length;session.state=total&&completed.size===total?"completed":"active";}
  function applyQueuedSteps(){for(const entry of state.stepBatch.changes.values()){const session=findDaySession(entry.key);if(!session)continue;for(const [stepID,checked] of entry.changes)applySessionStep(session,stepID,checked);}}
  function patchRoutineDay(){if(state.view!=="today"||state.form)return render();for(const person of list(state.day?.people)){for(const session of list(person.sessions)){const current=[...body().querySelectorAll("[data-rt-session-key]")].find(node=>node.dataset.rtSessionKey===sessionKey(session));if(current)current.replaceWith(sessionCard(session));}const head=[...body().querySelectorAll("[data-rt-person-id]")].find(node=>node.dataset.rtPersonId===String(person.id));if(head)head.textContent=personSummary(person);}}
  async function flushRoutineSteps(){
    if(state.stepBatch.flight)return state.stepBatch.flight;
    if(!state.stepBatch.changes.size)return;
    if(state.stepBatch.timer){clearTimeout(state.stepBatch.timer);state.stepBatch.timer=0;}
    const pending=[...state.stepBatch.changes.values()].map(entry=>({key:entry.key,routineId:entry.routineId,assignmentId:entry.assignmentId,changes:[...entry.changes.entries()].map(([stepId,checked])=>({stepId,checked}))}));
    state.stepBatch.changes.clear();
    const run=(async()=>{try{for(const entry of pending){const response=await request("/api/routines/occurrence",{op:"steps",routineId:entry.routineId,assignmentId:entry.assignmentId,date:state.date,steps:entry.changes});accept(response);applyQueuedSteps();}setStatus("Checklist updated.");patchRoutineDay();}catch(error){try{await refreshDay();applyQueuedSteps();patchRoutineDay();}catch(_){ }setStatus(error.message||"Could not save checklist changes.");}})();
    state.stepBatch.flight=run;
    try{return await run;}finally{state.stepBatch.flight=null;if(state.stepBatch.changes.size&&!state.stepBatch.timer)state.stepBatch.timer=setTimeout(()=>flushRoutineSteps(),80);}
  }
  function queueRoutineStep(session,stepID,checked){const key=sessionKey(session),live=findDaySession(key)||session;applySessionStep(live,stepID,checked);let entry=state.stepBatch.changes.get(key);if(!entry){entry={key,routineId:session.routineId,assignmentId:session.assignmentId,changes:new Map()};state.stepBatch.changes.set(key,entry);}entry.changes.set(String(stepID),!!checked);setStatus("Checklist updates pending…");patchRoutineDay();if(!state.stepBatch.timer&&!state.stepBatch.flight)state.stepBatch.timer=setTimeout(()=>flushRoutineSteps(),80);}
  async function afterQueuedRoutineSteps(run){await flushRoutineSteps();if(state.stepBatch.changes.size)await flushRoutineSteps();return run();}
  function sessionCard(session){const progress=core.progress(session),card=el("section","rt-session");card.dataset.rtSessionKey=sessionKey(session);const title=el("div","rt-session-title",`${session.time&&!session.allDay?session.time+" · ":""}${session.routineTitle||"Routine"}`);card.append(title);if(session.routineNote)card.append(el("p","rt-note",session.routineNote));const steps=el("div","rt-steps");const done=core.completed(session);for(const step of list(session.steps)){const label=el("label","rt-step"),check=document.createElement("input");check.type="checkbox";check.checked=done.has(String(step.id));check.disabled=state.busy||session.state==="skipped";check.addEventListener("change",()=>queueRoutineStep(session,step.id,check.checked));label.append(check,el("span","",step.text));steps.appendChild(label);}card.appendChild(steps);const summary=el("div","rt-progress",session.state==="completed"?"Complete":session.state==="skipped"?"Skipped":`${progress.done}/${progress.total} complete`);card.appendChild(summary);if(session.state==="active"){const actions=el("div","rt-actions");if(progress.total&&progress.done<progress.total)actions.appendChild(button("Complete routine","rt-action primary",()=>afterQueuedRoutineSteps(()=>mutate("/api/routines/occurrence",{op:"complete",routineId:session.routineId,assignmentId:session.assignmentId,date:state.date},"Routine completed."))));actions.appendChild(button("Skip","rt-action",()=>afterQueuedRoutineSteps(()=>mutate("/api/routines/occurrence",{op:"skip",routineId:session.routineId,assignmentId:session.assignmentId,date:state.date},"Routine skipped."))));card.appendChild(actions);}return card;}
  function personSummary(person){let done=0,total=0,complete=0;for(const session of list(person.sessions)){const progress=core.progress(session);done+=progress.done;total+=progress.total;if(session.state==="completed")complete++;}const sessions=list(person.sessions).length;return complete===sessions?`${person.name||"Household member"} · Complete`:`${person.name||"Household member"} · ${sessions} routine${sessions===1?"":"s"} · ${done}/${total} complete`;}
  function todayView(){const wrap=el("div","rt-view");wrap.append(dateControls(),el("div","rt-overview",state.date===core.dateKey(new Date())?`Today · ${humanDate(state.date)}`:humanDate(state.date)));const groups=list(state.day?.people);if(!groups.length){wrap.appendChild(el("div","rt-empty","No routines are due on this date."));return wrap;}if(state.initialDayExpansion){const first=groups.find(person=>list(person.sessions).some(session=>session.state==="active"&&core.progress(session).done<core.progress(session).total));if(first)state.expanded.add(String(first.id));state.initialDayExpansion=false;}for(const person of groups){const key=String(person.id),open=state.expanded.has(key),card=el("section","rt-person");const head=button(personSummary(person),"rt-person-toggle",()=>{if(state.expanded.has(key))state.expanded.delete(key);else state.expanded.add(key);render();});head.dataset.rtPersonId=key;head.setAttribute("aria-expanded",String(open));card.appendChild(head);if(open){for(const session of list(person.sessions))card.appendChild(sessionCard(session));}wrap.appendChild(card);}return wrap;}
  function scheduleDefaults(){return{kind:"weekdays",every:1,weekdays:["MO","TU","WE","TH","FR"],startOn:core.dateKey(new Date()),endOn:"",time:"",allDay:true,month:1,day:1};}
  function normalizedSchedule(value){const schedule={...scheduleDefaults(),...(value||{})};schedule.weekdays=list(schedule.weekdays);return schedule;}
  function defaultDraft(existing){const assignments=new Map();for(const assignment of list(existing?.assignments)){assignments.set(String(assignment.personId),{id:assignment.id||"",personId:String(assignment.personId),calendarEnabled:assignment.calendarEnabled!==false,schedule:normalizedSchedule(assignment.schedule)});}const first=assignments.values().next().value;return{ id:existing?.id||"",title:existing?.title||"",note:existing?.note||"",steps:list(existing?.steps).map(step=>step.text).join("\n"),assignments,template:normalizedSchedule(first?.schedule),templateCalendar:first?.calendarEnabled!==false};}
  function scheduleEditor(draft,assignment,personName){const wrap=el("section","rt-person-assignment");wrap.appendChild(el("div","rt-card-title",personName));const schedule=assignment.schedule;const cadence=select("Cadence",schedule.kind,[["days","Every N days"],["weekdays","Weekdays"],["weekly","Weekly"],["monthly","Monthly"],["yearly","Yearly"],["once","One time"]],value=>{schedule.kind=value;render();},`assignment-${assignment.personId}-cadence`);wrap.appendChild(cadence.wrap);if(schedule.kind!=="once"){const every=field(schedule.kind==="weekdays"?"Every N weeks":"Every",schedule.every,"numbers","1",false,`assignment-${assignment.personId}-every`);every.input.inputMode="numeric";every.input.addEventListener("input",()=>schedule.every=every.input.value);wrap.appendChild(every.wrap);}const start=field("Starts",schedule.startOn,"date","YYYY-MM-DD",false,`assignment-${assignment.personId}-start`),end=field("Ends (optional)",schedule.endOn,"date","YYYY-MM-DD",false,`assignment-${assignment.personId}-end`);start.input.addEventListener("input",()=>schedule.startOn=start.input.value);end.input.addEventListener("input",()=>schedule.endOn=end.input.value);wrap.append(start.wrap,end.wrap);
    if(schedule.kind==="weekly"){const weekday=el("div","rt-weekdays"),caption=el("span","","Weekdays");weekday.appendChild(caption);for(const [code,name] of [["MO","Mon"],["TU","Tue"],["WE","Wed"],["TH","Thu"],["FR","Fri"],["SA","Sat"],["SU","Sun"]]){const label=el("label","rt-mini-check"),check=document.createElement("input");check.type="checkbox";check.checked=schedule.weekdays.includes(code);check.addEventListener("change",()=>{schedule.weekdays=check.checked?[...schedule.weekdays,code]:schedule.weekdays.filter(v=>v!==code);});label.append(check,document.createTextNode(name));weekday.appendChild(label);}wrap.appendChild(weekday);}
    if(schedule.kind==="monthly"||schedule.kind==="yearly"){const day=field("Day of month",schedule.day,"numbers","1",false,`assignment-${assignment.personId}-day`);day.input.inputMode="numeric";day.input.addEventListener("input",()=>schedule.day=day.input.value);wrap.append(day.wrap,el("p","rt-note","Dates beyond a month’s length run on that month’s final day."));if(schedule.kind==="yearly"){const month=field("Month number",schedule.month,"numbers","1–12",false,`assignment-${assignment.personId}-month`);month.input.inputMode="numeric";month.input.addEventListener("input",()=>schedule.month=month.input.value);wrap.appendChild(month.wrap);}}
    const allDay=el("label","rt-check"),allDayInput=document.createElement("input");allDayInput.type="checkbox";focusKey(allDayInput,`assignment-${assignment.personId}-all-day`);allDayInput.checked=schedule.allDay!==false;allDayInput.addEventListener("change",()=>{schedule.allDay=allDayInput.checked;render();});allDay.append(allDayInput,document.createTextNode("All-day routine session"));wrap.appendChild(allDay);if(schedule.allDay===false){const clock=field("Time",schedule.time,"time","HH:MM",false,`assignment-${assignment.personId}-time`);clock.input.addEventListener("input",()=>schedule.time=clock.input.value);wrap.appendChild(clock.wrap);}const calendar=el("label","rt-check"),calendarInput=document.createElement("input");calendarInput.type="checkbox";focusKey(calendarInput,`assignment-${assignment.personId}-calendar`);calendarInput.checked=assignment.calendarEnabled!==false;calendarInput.addEventListener("change",()=>assignment.calendarEnabled=calendarInput.checked);calendar.append(calendarInput,document.createTextNode("Show this person’s sessions on Routines calendar"));wrap.appendChild(calendar);return wrap;}
  function routineForm(){const draft=state.form.draft,editing=state.form.kind==="edit",card=el("section","rt-card rt-form");card.appendChild(el("div","rt-card-title",editing?"Edit routine":"Add routine"));const title=field("Routine name",draft.title,"text","Example: Morning routine",false,"routine-title"),note=field("Optional note",draft.note,"text","A calm short reminder",true,"routine-note"),steps=field("Checklist steps",draft.steps,"text","One step per line · up to 30",true,"routine-steps");title.input.maxLength=120;note.input.maxLength=280;title.input.addEventListener("input",()=>draft.title=title.input.value);note.input.addEventListener("input",()=>draft.note=note.input.value);steps.input.addEventListener("input",()=>draft.steps=steps.input.value);const stepCount=el("p","rt-note",`${draft.steps.split(/\r?\n/).filter(v=>v.trim()).length}/30 steps`);steps.input.addEventListener("input",()=>stepCount.textContent=`${draft.steps.split(/\r?\n/).filter(v=>v.trim()).length}/30 steps`);card.append(title.wrap,note.wrap,steps.wrap,stepCount);
    const personBlock=el("div","rt-people-picker"),caption=el("span","","People and their schedules");personBlock.appendChild(caption);const active=people().filter(person=>person.state==="active");if(!active.length)personBlock.appendChild(el("p","rt-note","Add a shared household person in Dashboard Control first."));for(const person of active){const id=String(person.id),label=el("label","rt-mini-check"),check=document.createElement("input");check.type="checkbox";focusKey(check,`person-${id}`);check.checked=draft.assignments.has(id);check.addEventListener("change",()=>{if(check.checked)draft.assignments.set(id,{id:"",personId:id,calendarEnabled:draft.templateCalendar!==false,schedule:clone(draft.template)});else draft.assignments.delete(id);render();});label.append(check,document.createTextNode(person.name));personBlock.appendChild(label);if(draft.assignments.has(id))personBlock.appendChild(scheduleEditor(draft,draft.assignments.get(id),person.name));}card.appendChild(personBlock);if(draft.assignments.size>1){card.appendChild(button("Apply first selected schedule to all","rt-action",()=>{const base=clone(draft.assignments.values().next().value);for(const [id,assignment] of draft.assignments){assignment.schedule=clone(base.schedule);assignment.calendarEnabled=base.calendarEnabled;draft.assignments.set(id,assignment);}render();}));}
    const actions=el("div","rt-actions rt-form-actions");actions.append(button(editing?"Save routine":"Add routine","rt-action primary",()=>{const payload={op:editing?"update":"create",id:draft.id,title:draft.title,note:draft.note,steps:draft.steps.split(/\r?\n/).map(text=>({text})).filter(row=>row.text.trim()),assignments:[...draft.assignments.values()].map(assignment=>({id:assignment.id||"",personId:assignment.personId,calendarEnabled:assignment.calendarEnabled!==false,schedule:{...assignment.schedule,weekdays:[...list(assignment.schedule.weekdays)],every:Number(assignment.schedule.every)||1,day:Number(assignment.schedule.day)||1,month:Number(assignment.schedule.month)||1}}))};mutate("/api/routines/items",payload,editing?"Routine saved.":"Routine added.");}),button("Cancel","rt-action",()=>{state.form=null;hideOSK();render();}));card.appendChild(actions);return card;}
  function routinesView(){const wrap=el("div","rt-view"),actions=el("div","rt-actions");actions.append(button("Add routine","rt-action primary rt-add",()=>{state.form={kind:"create",draft:defaultDraft(null)};render();}),managePeopleButton("rt-action"));wrap.appendChild(actions);const active=routines().filter(item=>item.state==="active"),archived=routines().filter(item=>item.state==="archived");if(!active.length)wrap.appendChild(el("div","rt-empty","Create a routine, choose people, then set their schedules."));for(const item of active){const card=el("section","rt-card");const labels=list(item.assignments).map(assignment=>`${people().find(person=>String(person.id)===String(assignment.personId))?.name||"Person"}: ${core.scheduleLabel(assignment.schedule)}`);card.append(el("div","rt-card-title",item.title),el("p","rt-note",`${item.steps.length} steps · ${item.assignments.length} people`),el("p","rt-note",labels.join(" · ")));const actions=el("div","rt-actions");actions.append(button("Edit","rt-action",()=>{state.form={kind:"edit",draft:defaultDraft(item)};render();}),button("Archive","rt-action",()=>mutate("/api/routines/items",{op:"archive",id:item.id},"Routine archived.")),button("Delete","rt-action danger",()=>{state.confirm={kind:"routine",item};render();}));card.appendChild(actions);wrap.appendChild(card);}if(archived.length){const card=el("section","rt-card");card.appendChild(el("div","rt-card-title","Archived"));for(const item of archived)card.appendChild(button(`Restore ${item.title}`,"rt-action",()=>mutate("/api/routines/items",{op:"restore",id:item.id},"Routine restored.")));wrap.appendChild(card);}return wrap;}
  function historyView(){const wrap=el("section","rt-card"),rows=list(state.data?.history);wrap.append(el("div","rt-card-title","History"),el("p","rt-note","Completion and skip history is kept locally for 180 days."));if(!rows.length)wrap.appendChild(el("p","rt-note","No routine history yet."));else rows.slice(0,120).forEach(row=>{const date=row.date?humanDate(row.date):String(row.occurredAt||"").slice(0,10);wrap.appendChild(el("div","rt-history-row",`${date} · ${row.personName||"Household member"} · ${row.routineTitle||"Routine"} · ${row.action}`));});return wrap;}
  function settingsView(){const wrap=el("section","rt-card");wrap.append(el("div","rt-card-title","Routines calendar"),el("p","rt-note","Routines stay local even when calendar output is off."));const enabled=settings().calendarOutputEnabled!==false;wrap.appendChild(button(enabled?"Calendar output: On":"Calendar output: Off","rt-action"+(enabled?" primary":""),()=>mutate("/api/routines/settings",{calendarOutputEnabled:!enabled},"Routines settings saved.")));const horizon=Number(settings().calendarHorizonDays)||56;const options=el("div","rt-actions");for(const days of [28,56,84]){const node=button(`${days} day horizon`,"rt-action"+(days===horizon?" primary":""),()=>mutate("/api/routines/settings",{calendarHorizonDays:days},"Calendar horizon saved."));node.setAttribute("aria-pressed",String(days===horizon));options.appendChild(node);}wrap.append(options,managePeopleButton("rt-action"));return wrap;}
  function confirmation(){const layer=el("div","rt-confirm"),card=el("section","rt-card"),item=state.confirm.item;card.append(el("strong","",`Delete ${item.title}?`),el("p","rt-note","Future generated Routines calendar sessions will be removed. Completed local history remains for the 180-day history window."));card.append(el("div","rt-actions",button("Delete routine","rt-action danger",()=>mutate("/api/routines/items",{op:"delete",id:item.id},"Routine deleted.")),button("Keep routine","rt-action",()=>{state.confirm=null;render();})));layer.appendChild(card);return layer;}
  function render(){if(!isOpen()||!state.data)return;const focus=captureFormFocus();nav();const content=body();const view=state.form?routineForm():(state.view==="routines"?routinesView():state.view==="history"?historyView():state.view==="settings"?settingsView():todayView());content.replaceChildren(view);if(state.confirm)content.appendChild(confirmation());restoreFormFocus(focus);}
  async function openRoutines(options){if(isOpen())return;const shell=root();if(!shell)return;state.priorFocus=document.activeElement;state.date=core.dateKey(options?.date||new Date());state.view="today";state.form=null;state.confirm=null;state.expanded=new Set();state.initialDayExpansion=true;shell.hidden=false;shell.classList.add("show");shell.setAttribute("aria-hidden","false");if(typeof completeAppLauncherHandoff==="function")completeAppLauncherHandoff();if(typeof armOverlayAutoClose==="function")armOverlayAutoClose();if(window.DashGoAppDialog)window.DashGoAppDialog.focusInitial(shell,"#routines-close");else requestAnimationFrame(()=>document.getElementById("routines-close")?.focus?.());try{await load();}catch(error){state.data={people:[],routines:[],history:[],settings:{calendarOutputEnabled:true,calendarHorizonDays:56}};state.day={people:[]};setStatus(error.message||"Routines are unavailable.");render();}}
  function closeRoutines(){const shell=root();if(!shell||(typeof appLauncherHandoffActive==="function"&&appLauncherHandoffActive()))return;state.focusSerial++;if(state.stepBatch.timer)clearTimeout(state.stepBatch.timer);state.stepBatch.timer=0;state.stepBatch.changes.clear();hideOSK();state.form=null;state.confirm=null;shell.classList.remove("show");shell.hidden=true;shell.setAttribute("aria-hidden","true");if(typeof disarmOverlayAutoClose==="function")disarmOverlayAutoClose();if(typeof resumeUiAfterOverlay==="function"&&!(typeof overlayIsOpen==="function"&&overlayIsOpen()))resumeUiAfterOverlay();const trigger=document.getElementById("cblaunch");if(window.DashGoAppDialog)window.DashGoAppDialog.restoreFocus(state.priorFocus,trigger);else (trigger&&!trigger.hidden?trigger:state.priorFocus)?.focus?.();}
  function bindShell(){const shell=root(),close=document.getElementById("routines-close");if(!shell)return;if(close)bindTap(close,closeRoutines);bindTap(shell,closeRoutines,{ignore:event=>event.target!==shell});document.addEventListener("keydown",event=>{if(event.key!=="Escape"||!isOpen())return;event.preventDefault();if(state.confirm){state.confirm=null;render();}else if(state.form){state.form=null;hideOSK();render();}else closeRoutines();});}
  window.openRoutinesImpl=openRoutines;window.closeRoutines=closeRoutines;window.routinesIsOpen=isOpen;bindShell();
})();
