package main

import (
	"fmt"
	"os"
	"path/filepath"
	"slices"
	"strings"
	"time"

	"github.com/DashDashGoApp/Dash-Go/app/internal/fileio"
	"github.com/DashDashGoApp/Dash-Go/app/internal/jsonutil"
)

func (a *app) writeDemoConfigLocal() error {
	txt := fmt.Sprintf(`// Generated by dashboard-control-server --setup-demo-mode on %s.
window.DASHBOARD_LOCAL = {
  demoMode: true,
  lat: 41.8781,
  lon: -87.6298,
  locationName: "Chicago, IL",
  tempUnit: "fahrenheit",
  windUnit: "mph",
  theme: "basic",
  weatherProviders: ["openmeteo"],
  weatherDays: 7,
  refreshWxMinutes: 30,
  weatherAlerts: { enabled: true, refreshMinutes: 5, minSeverity: "moderate" },
  showEventMaps: true,
  showInteractiveMaps: false,
  fontPreset: "default",
  weatherIconStyle: "soft",
  seasonalDecor: "subtle",
  birthdays: [
    {name:"Avery",date:"04-12"},
    {name:"Jordan",date:"09-24"}
  ]
};
`, time.Now().Format(time.ANSIC))
	return fileio.WriteAtomic(a.configLocal, []byte(txt), 0644)
}

func (a *app) writeDemoMessages() error {
	compliments := map[string]any{
		"messages": []any{
			map[string]any{"id": 1, "text": "Demo mode is showing sample Chicago calendars, weather, and messages.", "weight": 10, "origin": "custom"},
			map[string]any{"id": 2, "text": "Tap a busy day to preview the day timeline popup.", "weight": 8, "origin": "custom"},
			map[string]any{"id": 3, "text": "Triple-tap the moon phase to open Dashboard Control and explore display and calendar settings.", "weight": 8, "origin": "custom"},
			map[string]any{"id": 4, "text": "Long events, recurring events, and multi-day trips are included in this demo.", "weight": 6, "origin": "custom"},
			map[string]any{"id": 5, "text": "Run the installer again to leave Demo Mode and configure your real dashboard.", "weight": 10, "origin": "custom"},
			map[string]any{"id": 6, "text": "Chicago weather is live when the network is available; sample calendars are local.", "weight": 7, "origin": "custom"},
		},
		"defaultsCleared": true, "defaultsSeeded": false, "removedDefaults": []any{}, "defaultEdits": map[string]any{}, "version": 4,
	}
	if err := fileio.WriteJSON(a.complimentsPath(), compliments); err != nil {
		return err
	}
	cache := map[string]any{
		"items": []any{
			map[string]any{"id": "demo-tip-calendar", "text": "Demo tip: multi-day bars line up with same-day events in the month grid.", "source": "demo", "nsfw": false, "weight": 4, "edited": false},
			map[string]any{"id": "demo-tip-weather", "text": "Demo tip: Weather uses key-free providers unless you add API keys later.", "source": "demo", "nsfw": false, "weight": 4, "edited": false},
			map[string]any{"id": "demo-tip-maps", "text": "Demo tip: Events with locations can show map previews when maps are enabled.", "source": "demo", "nsfw": false, "weight": 4, "edited": false},
			map[string]any{"id": "demo-tip-control", "text": "Demo tip: Triple-tap the moon phase to open Dashboard Control and explore settings.", "source": "demo", "nsfw": false, "weight": 5, "edited": false},
			map[string]any{"id": "demo-tip-install", "text": "Demo tip: Re-run the installer to reset Demo Mode and start fresh.", "source": "demo", "nsfw": false, "weight": 5, "edited": false},
		},
		"generatedAt": nowMillis(), "sources": []any{"demo"}, "enabled": []any{"demo"}, "sourceStatus": []any{map[string]any{"id": "demo", "ok": true, "count": 5}},
	}
	if err := fileio.WriteJSON(filepath.Join(a.configDir, "message-cache.json"), cache); err != nil {
		return err
	}
	_ = fileio.WriteJSON(filepath.Join(a.configDir, "message-sources.json"), map[string]any{"enabled": []any{"demo"}, "updatedAt": nowMillis()})
	_ = fileio.WriteJSON(filepath.Join(a.configDir, "message-cache-overrides.json"), map[string]any{"removed": []any{}, "edits": map[string]any{}})
	_ = fileio.WriteJSON(filepath.Join(a.configDir, "temp-messages.json"), []any{})
	_ = fileio.WriteJSON(filepath.Join(a.configDir, "scheduled-messages.json"), []any{})
	return nil
}

func (a *app) demoMessageLeaks() []string {
	paths := []string{a.complimentsPath(), filepath.Join(a.configDir, "message-cache.json"), filepath.Join(a.configDir, "temp-messages.json"), filepath.Join(a.configDir, "scheduled-messages.json")}
	leaks := []string{}
	for _, p := range paths {
		b, err := os.ReadFile(p)
		if err != nil {
			continue
		}
		text := string(b)
		for _, marker := range demoTextMarkers {
			if strings.Contains(text, marker) {
				leaks = append(leaks, filepath.Base(p)+": "+marker)
			}
		}
	}
	slices.Sort(leaks)
	return leaks
}

func (a *app) cleanDemoMessages() int {
	removed := 0
	paths := []string{a.complimentsPath(), filepath.Join(a.configDir, "message-cache.json"), filepath.Join(a.configDir, "temp-messages.json"), filepath.Join(a.configDir, "scheduled-messages.json")}
	for _, p := range paths {
		raw := a.readJSONDefault(p, nil)
		if raw == nil {
			continue
		}
		m := jsonutil.Map(raw)
		for _, key := range []string{"messages", "items"} {
			items := jsonutil.List(m[key])
			if len(items) == 0 {
				continue
			}
			keep := []any{}
			for _, it := range items {
				text := jsonutil.StringValue(jsonutil.Map(it)["text"])
				if isDemoText(text) {
					removed++
					continue
				}
				keep = append(keep, it)
			}
			m[key] = keep
		}
		_ = fileio.WriteJSON(p, m)
	}
	return removed
}

func isDemoText(text string) bool {
	for _, marker := range demoTextMarkers {
		if strings.Contains(text, marker) {
			return true
		}
	}
	return false
}
