package main

import "regexp"

// These expressions are intentionally package-level. Several run while parsing
// calendars, maps, diagnostics, and weather data; compiling them per record or
// request needlessly allocates and rebuilds the regexp program.
var (
	reDefaultCalendarKey   = regexp.MustCompile(`^[A-Z0-9_]+$`)
	reICSUIDSafe           = regexp.MustCompile(`[^A-Za-z0-9_-]+`)
	reHolidayDate          = regexp.MustCompile(`^DTSTART[^:]*:(\d{8})`)
	reISSLatitude          = regexp.MustCompile(`lat\s*:\s*([-0-9.]+)`)
	reISSLongitude         = regexp.MustCompile(`lon\s*:\s*([-0-9.]+)`)
	reHexSix               = regexp.MustCompile(`^[0-9a-fA-F]{6}$`)
	reHexColor             = regexp.MustCompile(`^#[0-9a-fA-F]{6}$`)
	reMonthDay             = regexp.MustCompile(`^\d{2}-\d{2}$`)
	reISODate              = regexp.MustCompile(`^\d{4}-\d{2}-\d{2}$`)
	reBackupFilenameSafe   = regexp.MustCompile(`[^0-9A-Za-z._-]+`)
	rePauseBeforeProfile   = regexp.MustCompile(`(?i)(\n\s*pauseWhileOpen\s*:\s*(?:true|false))\s*(\n\s*profile\s*:)`)
	rePauseProfilePair     = regexp.MustCompile(`(?i)\n\s*pauseWhileOpen\s*:\s*(?:true|false)\s*\n\s*profile\s*:`)
	reDashboardLocalObject = regexp.MustCompile(`(window\.DASHBOARD_LOCAL\s*=\s*\{\s*\n)`)
	reDemoMode             = regexp.MustCompile(`(?i)(["']?demoMode["']?\s*:\s*true\s*,?\s*)`)
	reANSI                 = regexp.MustCompile(`\x1b\[[0-9;]*m`)
	reDoctorLine           = regexp.MustCompile(`^(OK|FIXED|WARN|FAIL|BAD)\s+(.*)$`)
	reAbsoluteURL          = regexp.MustCompile(`^[a-zA-Z][a-zA-Z0-9+.-]*://`)
	reMapCacheExtension    = regexp.MustCompile(`(?i)\.(svg|png|jpg|jpeg|webp)$`)
	reMapCacheCoordinate   = regexp.MustCompile(`^(?:standard|hybrid)_z\d+_([pm]\d+\.\d+)_([pm]\d+\.\d+)$`)
	reWhitespace           = regexp.MustCompile(`\s+`)
	reControlChars         = regexp.MustCompile(`[\x00-\x1f]+`)
	reUSPostal             = regexp.MustCompile(`(?i)\b[A-Z]{2}\s+\d{5}(?:-\d{4})?\b`)
	reUSCountry            = regexp.MustCompile(`(?i)\b(United States|USA|US)\b`)
	reStreetNumber         = regexp.MustCompile(`^\d{1,7}\s+`)
	reStreetSuffix         = regexp.MustCompile(`(?i)\b(road|rd\.?|street|st\.?|avenue|ave\.?|drive|dr\.?|lane|ln\.?|court|ct\.?|boulevard|blvd\.?|highway|hwy\.?|parkway|pkwy\.?)\b`)
	reUSCountrySuffix      = regexp.MustCompile(`(?i),?\s*(United States of America|United States|USA|US)\s*$`)
	reTimeOfDay            = regexp.MustCompile(`^\d{1,2}:\d{2}$`)
	reBirthdayList         = regexp.MustCompile(`(?ms)\bbirthdays\s*:\s*(\[[^\]]*\])`)
	reBirthdayListLine     = regexp.MustCompile(`(?ms)^(\s*)birthdays\s*:\s*\[[^\]]*\]\s*,?`)
	reFeedExpiry           = regexp.MustCompile(`^(30|60|120|360|720|1440)m$`)
	reNSFWPrefix           = regexp.MustCompile(`(?i)^nsfw:\s*`)
	reConfigLatitude       = regexp.MustCompile(`\blat:\s*-?\d`)
	reConfigLongitude      = regexp.MustCompile(`\blon:\s*-?\d`)
	reLocationName         = regexp.MustCompile(`locationName:\s*"([^"]*)"`)
	reSkyLatitude          = regexp.MustCompile(`\blat:\s*([-0-9.]+)`)
	reSkyLongitude         = regexp.MustCompile(`\blon:\s*([-0-9.]+)`)
	reFirstDecimal         = regexp.MustCompile(`([0-9]+(?:\.[0-9]+)?)`)
	reJSStringArrayItem    = regexp.MustCompile(`["']([^"']+)["']`)
	reJSStringMapItem      = regexp.MustCompile(`(?m)["']?([A-Za-z0-9_-]+)["']?\s*:\s*["']([^"']*)["']`)
	reWeatherSnow          = regexp.MustCompile(`snow|sleet|ice|flurr`)
	reWeatherRain          = regexp.MustCompile(`rain|shower|drizzle`)
	reWeatherFog           = regexp.MustCompile(`fog|mist|haze`)
	reFirstNumber          = regexp.MustCompile(`[\d.]+`)
)
